import getCurrentUser from "./actions/getUser";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import ToastProvider from "./toastProvider/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hotel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar currentUser={currentUser} /> */}
        <ToastProvider />
        {children}
      </body>
    </html>
  );
}
